version: '3'

services:
  pgoberon:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgoberon'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
  
volumes:
  pg-data: